#!/bin/sh --

sudo hypercorn app -b '0.0.0.0:443' --certfile '/etc/letsencrypt/live/localraspberrypi.reeshill.net/fullchain.pem' --keyfile '/etc/letsencrypt/live/localraspberrypi.reeshill.net/privkey.pem'
